### PR TITLE
Updating version of conventional-changelog.

### PR DESCRIPTION
**Pull request by dfbaskin**
Ultimately trying to fix this issue:
https://github.com/semantic-release/semantic-release/issues/363

### CODE REVIEW

**Comment by obartra** [comment]
any updates on this?

**Comment by buehler** [comment]
Please merge 😱 
It's pretty ugly with that error :-(

**Comment by dfbaskin** [comment]
So @bahmutov pointed me to this alternate plugin:
https://github.com/bahmutov/github-post-release

It seems to work nicely and is more up-to-date.

**Comment by gr2m** [comment]
hey folks I’m looking into this now, I’ll help out maintaining semantic-release moving forward and would appreciate more help :)

**Comment by gr2m** [comment]
I’ll keep you all posted in this issue moving forward: https://github.com/semantic-release/semantic-release/issues/411 Thanks for your patience and if you could help triaging open issues / PRs and mention me in the ones you think are most urgent, I’d appreciate it <3

**Pull request closed without merging**
